#!/usr/bin/env tclsh
### compile + run program -*- Tcl -*-

set opts "-g -DDEBUG_GC"
set moreopts ""
set filename 0
set args ""
set i 0

foreach x $argv {
    switch $x {
	-O {set opts "-O3 -fomit-frame-pointer -fno-strict-aliasing -fwrapv -DUNSAFE"}
	-m32 {set moreopts "$moreopts -m32"}
	default {
	    set filename $x
	    set args [lrange $argv [expr $i + 1] $argc] 
	    break
	}
    }
    set i [expr $i + 1]
}

if {$filename == 0} {
    puts "missing filename"
    exit 1
}

if {! [file exists $filename]} {
    puts "no such file"
    exit 1
}

set bfile [file tail $filename]
set xfile [file rootname $bfile]
set cfile "${xfile}.c"

if {[file extension $filename] != ".c"} {
    if {[catch {exec ./pc -q -n $filename -o $cfile >&@ stdout} result]} {
	puts stderr $result
	exit 1
    }
}

eval exec gcc -std=gnu99 -Ilib -I. $opts $moreopts $cfile -o $xfile -lm -lrt >@ stdout

if {[catch {eval exec "./${xfile}" $args >@ stdout} result]} {
    puts stderr $result
    exit 1
}

if {$result != ""} {
    puts $result
}


